### ISSUE TITLE
need www.istio.io -> istio.io canonalization redirect

### ISSUE THREAD

**Issue by ldemailly** [istio/admin-sites#20]
google analytics is complaining:

"Property istio.io is receiving data from redundant hostnames. Some of the redundant hostnames are:
istio.io
www.istio.io
Redundant hostnames are counted as separate rows in reports, so hits that are going to the same page on your site from different hostnames will be split into multiple rows. With data split across multiple rows, traffic to specific pages will appear lower than it actually is.

To avoid this problem, consider setting up a 301 redirect from one of your redundant hostnames to the other, or create a search-and-replace filter that strips "www." from hostnames.
"

likewise
View All Web Site Data is receiving hits from multiple pages that might serve the same content. Some examples are:
/docs/
/docs/index.html

maybe we should redirect and hide the index.html (maybe that should be fixed in istio/istio.github.io )

cc @geeknoid fyi

**Comment by geeknoid** [comment]
I'll change the web site content and Jekyll logic to stop generating references to index.html and just point to the containing directory. This is mostly related to the left-hand nav links and the various generated TOC pages throughout.

I seem to recall there's also some Jekyll options around helping normalizing the use or no use of index.html stuff. I'll check on that.

I am suprised that the analytics are complaining about this stuff. I specifically configured the Custom Search Engine stuff to treat http://istio.io, https://istio.io, http://www.istio.io and https://www.istio.io as all the same.

**Comment by ldemailly** [comment]
I asked varun access to config analytics as it can also normalize, but not having both is good

**Comment by ayj** [comment]
#21 adds the missing 301 redirect.

**Comment by ldemailly** [comment]
I think this is done ? (reopen if I'm mistaken)
