### ISSUE TITLE
Use Istio

### ISSUE THREAD

**Issue by geeknoid** [istio/admin-sites#28]
I believe we could update what this repo is doing to use Istio instead of its current approach.

**Comment by geeknoid** [comment]
I'm suggesting we just do what we can to run as much of this on Istio as we can, including building something like a cache.

Consider this a tracking bug. Even if we don't fix this right now, we definitely need to be able to run our own web site with our own bits.

**Comment by ldemailly** [comment]
Istio isnt really about static content served over the internet so this doesn’t seem like a priority for now. maybe once the site is more dynamic or we run out of hi pri tasks.

**Comment by ayj** [comment]
istio.io` website content would be better served by a CDN. Kubernetes switched k8s.io over to  https://www.netlify.com and only handle subdomain redirects through nginx proxy.

**Comment by ldemailly** [comment]
I'm testing the waters with #32

**Comment by ldemailly** [comment]
After which we should switch the ingress for istio.io to istio/envoy for further dogfooding
